ZStandard: Introduce fd wrapper
google/sandboxed-api pull request #108
Opened 2022-02-02 21:55 UTC by oshogbo

The goal is to use a file descriptor as an input for ZStandard
library. Thanks to that we shouldn't send a chunk of memory over
expensive protocol.

Please notice this change depends on:
https://github.com/google/sandboxed-api/pull/106
https://github.com/google/sandboxed-api/pull/107

2022-02-03 17:15 UTC, cblichmann requested changes
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/108)* status: all files reviewed, 13 unresolved discussions (waiting on @oshogbo)

___
*[contrib/zstd/sandboxed.h, line 24 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-SrHK2AxPzlX7n38K:-Mv-SrHL1jY6WsqOHHql:br3ag0z) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/sandboxed.h#L24)):*
> ```objc
> 
> #include "sapi_zstd.sapi.h"  // NOLINT(build/include)
> #include "absl/flags/flag.h"
> ```

Move these two to `main.cc`.

Like I said in the other PR, sorry for not being clearer about this earlier.



_Code quote:_
```objc
#include "absl/flags/flag.h"
#include "absl/flags/parse.h"
```
___
*[contrib/zstd/example/main.cc, line 35 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-ThJs4356H2QI1tbE:-Mv-ThJs4356H2QI1tbF:b76quf2) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/example/main.cc#L35)):*
> ```cpp
>   std::ifstream infile(infile_s, std::ios::binary);
>   if (!infile.is_open()) {
>     return absl::UnavailableError(absl::StrCat(("Unable to open ", infile_s)));
> ```

Remove one level of braces: `absl::StrCat("Unable to open ", infile_s)`

Also below in this file.



_Code quote:_
```cpp
absl::StrCat(("Unable to open ", infile_s))
```
___
*[contrib/zstd/example/main.cc, line 44 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-T9_m24jdCvTKOnQr:-Mv-T9_n-vwlLooMAAIo:buceu95) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/example/main.cc#L44)):*
> ```cpp
>   if (absl::GetFlag(FLAGS_memory_mode) && absl::GetFlag(FLAGS_decompress)) {
>     return DecompressInMemory(api, infile, outfile);
>   } else if (absl::GetFlag(FLAGS_memory_mode) &&
> ```

Totally optional (pet peeve of mine): If the code already exits the current scope in the previous {}-block, this `else` is not needed.



_Code quote:_
```cpp
else
```
___
*[contrib/zstd/test/zstd_test.cc, line 284 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-Tv1pAtPE2Cq40Pu_:-Mv-Tv1pAtPE2Cq40Pua:b-3yfm9r) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/test/zstd_test.cc#L284)):*
> ```cpp
> 
>   status = DecompressStream(api, inmiddle, outfile);
>   ASSERT_THAT(status, IsOk()) << "Unable to decompress decompress";
> ```

Brought to you by the "Department of Redundancy Department" :-D



_Code quote:_
```cpp
decompress
```
___
*[contrib/zstd/test/zstd_test.cc, line 298 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-Uxnv70a4Ax-upL0s:-Mv-Uxny6Ufm8floKaaq:b-me88zp) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/test/zstd_test.cc#L298)):*
> ```cpp
>   absl::StatusOr<std::string> path =
>       sapi::CreateNamedTempFileAndClose("out.zstd");
>   ASSERT_THAT(path, IsOk()) << "Could not create temp output file";
> ```

We'll get similar results by using `SAPI_ASSERT_OK_AND_ASSIGN()`.
Caveat: It does not support printing extra error log messages.



_Code quote:_
```cpp
ASSERT_THAT(path, IsOk())
```
___
*[contrib/zstd/test/zstd_test.cc, line 311 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-UJAl0d25-qSnTdTg:-Mv-UJAl0d25-qSnTdTh:bkobc2w) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/test/zstd_test.cc#L311)):*
> ```cpp
> 
>   off_t inpos = lseek(infd.GetValue(), 0, SEEK_END);
>   ASSERT_GE(inpos, 0);
> ```

Optional: The `ASSERT`s here should really be `EXPECT`s.



_Code quote:_
```cpp
  off_t inpos = lseek(infd.GetValue(), 0, SEEK_END);
  ASSERT_GE(inpos, 0);
  off_t outpos = lseek(outfd.GetValue(), 0, SEEK_END);
  ASSERT_GE(outpos, 0);

  ASSERT_LT(outpos, inpos);
```
___
*[contrib/zstd/test/zstd_test.cc, line 373 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-Vpxy5-Uy-92msKzF:-Mv-Vpxy5-Uy-92msKzG:bhacvp4) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/test/zstd_test.cc#L373)):*
> ```cpp
>   sapi::v::Fd outmiddlefd(open(middle_s.c_str(), O_WRONLY));
>   ASSERT_GE(outmiddlefd.GetValue(), 0);
> ```

To auto-cleanup the FDs you can use an `absl::Cleanup` here. E.g. for `outmiddlefd`:

```
absl::Cleanup outmiddlefd_cleanup = [&outmiddlefd] { outmiddlefd.CloseLocalFd(); };
```
___
*[contrib/zstd/test/zstd_test.cc, line 398 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-VkYC2_GpdjSbUF2_:-Mv-VkYC2_GpdjSbUF2a:b-pvcdq) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/test/zstd_test.cc#L398)):*
> ```cpp
> 
>   outfd.CloseLocalFd();
>   outmiddlefd.CloseLocalFd();
> ```

`inmiddlefd`?
___
*[contrib/zstd/utils/utils_zstd.cc, line 183 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-Y1Lz2lytMed_qVBi:-Mv-Y1Lz2lytMed_qVBj:b-c3renu) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/utils/utils_zstd.cc#L183)):*
> ```cpp
> }
> 
> absl::Status DecompressStream(ZstdApi& api, std::ifstream& in_file,
> ```

The parameter name is different from the header. Also for `CompressStream` if I see this correctly. I.e. `in_stream` vs `in_file`.



_Code quote:_
```cpp
in_file
```
___
*[contrib/zstd/utils/utils_zstd.cc, line 245 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-YOkF3JN_2rCQsltw:-Mv-YOkI0Y6HE2sARwb6:b-x1vdeq) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/utils/utils_zstd.cc#L245)):*
> ```cpp
> absl::Status CompressInMemoryFD(ZstdApi& api, sapi::v::Fd& infd,
>                                 sapi::v::Fd& outfd, int level) {
>   if (!api.GetSandbox()->TransferToSandboxee(&infd).ok() ||
> ```

Optional: `SAPI_RETURN_IF_ERROR()`, which will return the exact error from the operation.



_Code quote:_
```cpp
api.GetSandbox()->TransferToSandboxee(&infd)
```
___
*[contrib/zstd/utils/utils_zstd.cc, line 286 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-YfK202cE_BKIDGNc:-Mv-YfK202cE_BKIDGNd:b-bjtogd) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/utils/utils_zstd.cc#L286)):*
> ```cpp
> absl::Status CompressStreamFD(ZstdApi& api, sapi::v::Fd& infd,
>                               sapi::v::Fd& outfd, int level) {
>   SAPI_ASSIGN_OR_RETURN(ZSTD_CCtx * cctx, api.ZSTD_createCCtx());
> ```

Clang-Format gets this wrong. Leave it if your clang-format also does this.



_Code quote:_
```cpp
ZSTD_CCtx * cctx
```
___
*[contrib/zstd/wrapper/CMakeLists.txt, line 26 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-ZGIB8ae6A2lbq5RA:-Mv-ZGIB8ae6A2lbq5RB:b-snx0g0) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/wrapper/CMakeLists.txt#L26)):*
> ```CMake
> 
> target_include_directories(wrapper_zstd PUBLIC
>   ${libzstd_INCLUDE_DIR}
> ```

If you use `"${SAPI_SOURCE_DIR}"` here, we can include all headers (except the generated ones) by their longer path (like `contrib/zstd/wrapper_zstd.h`).

Rationale: Internally, we have all third-party/open-source code in our mono-repo in sub-directory `third_party/` and always use absolute includes (e.g. for Abseil `#include "third_party/absl/strings/string_view.h"). Another tool (Copybara) then transforms the code back and forth for GitHub.
___
*[contrib/zstd/wrapper/wrapper_zstd.cc, line 28 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-_EUyDc-79cUZhJDY:-Mv-_EV2CrEjiBwyqw6S:bgz59zj) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/wrapper/wrapper_zstd.cc#L28)):*
> ```cpp
> [...]

2022-02-04 08:14 UTC, cblichmann reviewed
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/108)* status: all files reviewed, 6 unresolved discussions (waiting on @oshogbo)



<!-- Sent from Reviewable.io -->

2022-02-04 09:53 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/108)* status: 2 of 9 files reviewed, 6 unresolved discussions (waiting on @cblichmann and @oshogbo)

___
*[contrib/zstd/sandboxed.h, line 24 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-SrHK2AxPzlX7n38K:-Mv-kOOU5s7E2aI6AZU3:b-e49jyp) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/sandboxed.h#L24)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Move these two to `main.cc`.

Like I said in the other PR, sorry for not being clearer about this earlier.
</blockquote></details>

This is addressed in other PR:
https://github.com/google/sandboxed-api/pull/107/commits/7af8f58e4802469e5c59d4d23fce5f330aac4933
___
*[contrib/zstd/example/main.cc, line 35 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-ThJs4356H2QI1tbE:-Mv-klPFBm_5ZmPm15Tk:bt2vr1b) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/example/main.cc#L35)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Remove one level of braces: `absl::StrCat("Unable to open ", infile_s)`

Also below in this file.
</blockquote></details>

Fixed.
___
*[contrib/zstd/example/main.cc, line 44 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-T9_m24jdCvTKOnQr:-Mv-l-E405drCSA7FjOo:bktdzy6) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/example/main.cc#L44)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Totally optional (pet peeve of mine): If the code already exits the current scope in the previous {}-block, this `else` is not needed.
</blockquote></details>

I'm not sure I follow.
___
*[contrib/zstd/test/zstd_test.cc, line 284 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-Tv1pAtPE2Cq40Pu_:-Mv-lA1b12zWRr0z3WIo:b-572suf) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/test/zstd_test.cc#L284)):*
> decompress
Fixed <face palm>
___
*[contrib/zstd/test/zstd_test.cc, line 298 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-Uxnv70a4Ax-upL0s:-Mv-tXqF2ZKVYyfo_n9c:b-w1xz2m) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/test/zstd_test.cc#L298)):*
> SAPI_ASSERT_OK_AND_ASSIGN
Fixed.
___
*[contrib/zstd/test/zstd_test.cc, line 311 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-UJAl0d25-qSnTdTg:-Mv-mSJEBtJolD8vDADy:b-tti2cv) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/test/zstd_test.cc#L311)):*
> EXPECTs
Fixed.
___
*[contrib/zstd/test/zstd_test.cc, line 373 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-Vpxy5-Uy-92msKzF:-Mv-nIeSCybRPDRSvrL8:byj0u7j) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/test/zstd_test.cc#L373)):*
> absl::Cleanup
But absl::cleanup is called when the function exists, I'm just ensuring here to not reuse the fd. If I understand correctly the sapi::v::Fd will close the file descriptor automatically.
___
*[contrib/zstd/test/zstd_test.cc, line 398 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-VkYC2_GpdjSbUF2_:-Mv-o6cE8RWlI-II-PJS:b-no6msb) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/test/zstd_test.cc#L398)):*
> inmiddlefd
Fixed.
___
*[contrib/zstd/utils/utils_zstd.cc, line 183 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-Y1Lz2lytMed_qVBi:-Mv-taQj7vnuT44vwcir:b-4nmcl0) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/utils/utils_zstd.cc#L183)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

The parameter name is different from the header. Also for `CompressStream` if I see this correctly. I.e. `in_stream` vs `in_file`.
</blockquote></details>

This is addressed in other PR: https://github.com/google/sandboxed-api/pull/106/commits/d2a8c8a1eafb411a58ca8c7094b76adeb1170c1e
___
*[contrib/zstd/utils/utils_zstd.cc, line 286 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-YfK202cE_BKIDGNc:-Mv-upRO594VSNVU7j5Q:bt2vr1b) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/utils/utils_zstd.cc#L286)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Clang-Format gets this wrong. Leave it if your clang-format also does this.
</blockquote></details>

Fixed.
___
*[contrib/zstd/wrapper/CMakeLists.txt, line 26 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-ZGIB8ae6A2lbq5RA:-Mv-vRD2-7VvpxeDn_oa:bmbw8jp) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/wrapper/CMakeLists.txt#L26)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

If you use `"${SAPI_SOURCE_DIR}"` here, we can include all headers (except the generated ones) by their longer path (like `contrib/zstd/wrapper_zstd.h`).

Rationale: Internally, we have all third-party/open-source code in our mono-repo in sub-directory `third_party/` and always use absolute includes (e.g. for Abseil `#include "third_party/absl/strings/string_view.h"). Another tool (Copybara) then transforms the code back and forth for GitHub.
</blockquote></details>

So I'm not sure if I follow.
If I understand correctly the SAPI_SOURCE_DIR is a directory where SAPI is.

In wrapper_zstd.cc I have to include zstd.h file which is part of libzstd.
The libzstd_INCLUDE_DIR points to "${libzstd_SOURCE_DIR}/lib" which isn't a part of the SAPI, its fetched from network.

So if I won't point to the build directory this won't work right?
___
*[contrib/zstd/wrapper/wrapper_zstd.cc, line 28 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-_EUyDc-79cUZhJDY:-Mv-xF2FBnzm9sepYBHo:b-pllxk1) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/wrapper/wrapper_zstd.cc#L28)):*
> constexpr size_t
Fixed.


<!-- Sent from Reviewable.io -->

2022-02-04 09:53 UTC, oshogbo reviewed
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/108)* status: 2 of 9 files reviewed, 6 unresolved discussions (waiting on @cblichmann)

___
*[contrib/zstd/utils/utils_zstd.cc, line 245 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-YOkF3JN_2rCQsltw:-Mv38pg43IJHfp_FD1Xv:b2g7gui) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/utils/utils_zstd.cc#L245)):*
> TransferToSandboxee
Fixed.


<!-- Sent from Reviewable.io -->

2022-02-07 16:29 UTC, cblichmann reviewed
> Reviewed 7 of 7 files at r3.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/108)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @cblichmann and @oshogbo)

___
*[contrib/zstd/example/main.cc, line 44 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-T9_m24jdCvTKOnQr:-MvJz2UX87ySytnCJwMf:b-d1k1xz) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/example/main.cc#L44)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I'm not sure I follow.
</blockquote></details>

Basically this
```
if (condition) {
  return kSomeValue;
} else if (other_condition) {
  return kSomeOtherValue;
} else {
  return kThirdValue;
}
```

Is always equivalent to
```
if (condition) {
  return kSomeValue;
}
if (other_condition) {
  return kSomeOtherValue;
}
return kThirdValue;
```

I find the latter much easier to reason about when reading top to bottom. Plus you'll always have a default case when extending the list of conditions later.

But like I said, totally optional.
___
*[contrib/zstd/wrapper/CMakeLists.txt, line 26 at r1](https://reviewable.io/reviews/google/sandboxed-api/108#-Mv-ZGIB8ae6A2lbq5RA:-MvK-c0p-bE1bgSRRdx-:brali3s) ([raw file](https://github.com/google/sandboxed-api/blob/b3cbf979ff41bdd897c0ee7af89cda0dbce442b5/contrib/zstd/wrapper/CMakeLists.txt#L26)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

So I'm not sure if I follow.
If I understand correctly the SAPI_SOURCE_DIR is a directory where SAPI is.

In wrapper_zstd.cc I have to include zstd.h file which is part of libzstd.
The libzstd_INCLUDE_DIR points to "${libzstd_SOURCE_DIR}/lib" which isn't a part of the SAPI, its fetched from network.

So if I won't point to the build directory this won't work right?
</blockquote></details>

Sorry, I should've phrased that better. We should add `"${SAPI_SOURCE_DIR}"` to the list and then refer to the longer paths where possible. So for the imported zstd itself, nothing changes, only the `contrib/zstd` headers get included by their longer paths.


<!-- Sent from Reviewable.io -->

2022-02-09 12:56 UTC, cblichmann reviewed
> Reviewed 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/108)* status: all files reviewed, 1 unresolved discussion (waiting on @cblichmann)



<!-- Sent from Reviewable.io -->

2022-02-09 15:48 UTC, merged