Initial commit of file support
google/sandboxed-api pull request #124
Opened 2022-02-18 01:04 UTC by DemiMarie

This only opens and closes a handle, and does not do anything interesting.

2022-02-18 06:55 UTC, DemiMarie commented
The test now manages to print out the output of `file(1)` on itself, which is interesting.

2022-02-22 10:48 UTC, cblichmann requested changes

2022-02-22 10:48 UTC, cblichmann commented on contrib/file/file_sapi_test.cc
> +  std::cerr << "Loaded!" << std::endl;
Remove these debug messages

2022-02-22 10:48 UTC, cblichmann commented on contrib/file/file_sapi.h
> +            __NR_openat,
Use `AllowOpen()` instead. That will allow both `openat()` and plain `open()`. glibc may use either, depending on its version.

2022-02-22 10:48 UTC, cblichmann commented on contrib/file/file_sapi.h
> +        .AllowMmap()
Perhaps use `AddPolicyOnMmap()` to restrict to the mapping to be read-only and no-exec?

2022-02-22 10:48 UTC, cblichmann commented on contrib/file/file_sapi.h
> +    for (auto p : {"/etc/magic.mgc", "/usr/share/misc/magic.mgc"}) {
My system has
```
/usr/lib/file/magic.mgc
/usr/share/file/magic.mgc
/usr/share/misc/magic.mgc
```

2022-02-22 10:48 UTC, cblichmann commented on contrib/file/file_sapi.h
> +      if (::lstat64(p, &st) == 0 && S_ISREG(st.st_mode)) builder.AddFile(p);
Use `sapi::file_util::fileops::Exists()` here.

2022-02-22 10:48 UTC, cblichmann commented on contrib/file/CMakeLists.txt
> +gtest_discover_tests(file_sapi_test PROPERTIES ENVIRONMENT "TEST_FILES_DIR=${PROJECT_SOURCE_DIR}/testdata")
This should only be enabled if we're building the tests `SAPI_ENABLE_TESTS`

2022-02-22 10:48 UTC, cblichmann commented on contrib/file/CMakeLists.txt
> +add_sapi_library(file_sapi
Please add an alias library `sapi_contrib::file`

2022-05-04 08:18 UTC, closed without merging