Simple libidn2 wrapper
google/sandboxed-api pull request #96
Opened 2022-01-20 19:08 UTC by DemiMarie

This adds a simple wrapper library around libidn2, including a wrapper
class.

2022-01-25 14:29 UTC, cblichmann requested changes
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/96)* status: 0 of 2 files reviewed, 22 unresolved discussions (waiting on @cblichmann and @DemiMarie)

___
*[contrib/libidn2/CMakeLists.txt, line 1 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGUJSF5dftGDvfsGb3:-MuGUJSGBFYm2UMqX3jk:b1fe9uk) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/CMakeLists.txt#L1)):*
> ```CMake
> # Copyright 2021 Google LLC
> ```

Use 2022 for new files
___
*[contrib/libidn2/CMakeLists.txt, line 15 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGUNyQC0aRdSLnDBu4:-MuGUNyQC0aRdSLnDBu5:b-h761k7) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/CMakeLists.txt#L15)):*
> ```CMake
> # limitations under the License.
> 
> cmake_minimum_required(VERSION 3.10)
> ```

Please use 3.13. I have a pending PR (#98) that changes the minimum required version to that. 3.13 is included in Debian Buster.
___
*[contrib/libidn2/CMakeLists.txt, line 36 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGUZR06Jl7iW5xF7MH:-MuGUZR06Jl7iW5xF7MI:b3ur3v0) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/CMakeLists.txt#L36)):*
> ```CMake
>   FUNCTIONS idn2_lookup_u8 idn2_register_u8
>             idn2_strerror idn2_strerror_name
> 	    idn2_free idn2_to_ascii_8z
> ```

Formatting: Convert all tabs to spaces
___
*[contrib/libidn2/CMakeLists.txt, line 38 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGUjJv4KAzxMyMleZu:-MuGUjJv4KAzxMyMleZv:batznaa) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/CMakeLists.txt#L38)):*
> ```CMake
> 	    idn2_free idn2_to_ascii_8z
> 	    idn2_to_unicode_8z8z
>   INPUTS /usr/include/idn2.h
> ```

Does the `PkgConfig` module give us a more distribution-independent way to obtain the full path to the `idn2.h` header?
___
*[contrib/libidn2/CMakeLists.txt, line 52 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGV82y3ZgzopAZ1qYd:-MuGV82y3ZgzopAZ1qYe:b-piu5gn) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/CMakeLists.txt#L52)):*
> ```CMake
> )
> 
> target_link_options(simple PRIVATE -Wl,--allow-shlib-undefined)
> ```

This warrants a comment. I.e. why do we need this?
___
*[contrib/libidn2/CMakeLists.txt, line 58 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGVI215ZCoHHiDdYgc:-MuGVI215ZCoHHiDdYgd:b1cmtpo) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/CMakeLists.txt#L58)):*
> ```CMake
>   idn2
>   sapi::base
>   gtest
> ```

See my comment in `simple.cc`
___
*[contrib/libidn2/simple.cc, line 1 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGVL4o6MedpxcY6V_L:-MuGVL4o6MedpxcY6V_M:bb6ht37) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L1)):*
> ```cpp
> // Copyright 2021 Google LLC
> ```

2022
___
*[contrib/libidn2/simple.cc, line 29 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGVQRs73BH0wZA9n1A:-MuGVQRs73BH0wZA9n1B:b-4uiyv9) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L29)):*
> ```cpp
> class Idn2SapiSandbox : public IDN2Sandbox {
>  public:
>   Idn2SapiSandbox() : IDN2Sandbox() {}
> ```

Either remove, or use ` = default;`
___
*[contrib/libidn2/simple.cc, line 32 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGVXfS6ZfISy-5ozMq:-MuGVXfT9R9bm6iFSj6J:bysj5cd) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L32)):*
> ```cpp
> 
>   std::unique_ptr<sandbox2::Policy> ModifyPolicy(
>       sandbox2::PolicyBuilder *) override {
> ```

The Google style guide leaves it open whether `*` and `&` should be closer to the type or not. SAPI is a bit more oppinionated: Prefer to keep them close to the type.
See https://github.com/google/sandboxed-api/blob/main/.clang-format#L5
___
*[contrib/libidn2/simple.cc, line 50 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGWbgj5-r2aPQmmOeN:-MuGWbgj5-r2aPQmmOeO:b-pilouk) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L50)):*
> ```cpp
> 
> class IDN2Lib {
>   Idn2SapiSandbox *sandbox;
> ```

The declaration order of a class should be `public`, `protected`, `private`. We always spell out `private`, even if that's the only block in a class (https://google.github.io/styleguide/cppguide.html#Declaration_Order).

Additionally, members should be declared below functions and end with an underscore (https://google.github.io/styleguide/cppguide.html#Variable_Names).
___
*[contrib/libidn2/simple.cc, line 52 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGXZTDE5xnX3nHjeVN:-MuGXZTDE5xnX3nHjeVO:bahykww) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L52)):*
> ```cpp
>   Idn2SapiSandbox *sandbox;
>   IDN2Api *api;
>   absl::StatusOr<std::string> sapi_generic(
> ```

Function names should use UpperCamelCase (https://google.github.io/styleguide/cppguide.html#Function_Names).
___
*[contrib/libidn2/simple.cc, line 56 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGYM6K59s3Ffqg3C5Z:-MuGYM6K59s3Ffqg3C5_:b-5ivl3z) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L56)):*
> ```cpp
>       absl::StatusOr<int> (IDN2Api::*cb)(sapi::v::Ptr *input,
>                                          sapi::v::Ptr *output, int flags));
>   absl::StatusOr<std::string> process_errors(absl::StatusOr<int> status,
> ```

Prefer `const absl::StatusOr<int>&` here.  We don't consider`absl::Status` and friends to be small enough to incur the cost of copying. Internally, an `absl::Status`/`absl::StatusOr<T>` may even contain a full stack trace.



_Code quote:_
```cpp
absl::StatusOr<int>
```
___
*[contrib/libidn2/simple.cc, line 64 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuG_1eO88dJlNdfgYZJ:-MuG_1eO88dJlNdfgYZK:b-wvnid1) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L64)):*
> ```cpp
>   IDN2Lib(IDN2Lib &other) = delete;
>   IDN2Lib(const IDN2Lib &other) = delete;
>   IDN2Lib(Idn2SapiSandbox *sandbox, IDN2Api *api)
> ```

I think it would be sufficient to accept an `Idn2SapiSandbox` as a mutable reference and create an `IDN2Api` ourselves here.
___
*[contrib/libidn2/simple.cc, line 67 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuG_Wqr-_kkaIrPu4Li:-MuG_Wqr-_kkaIrPu4Lj:b-j4tviv) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L67)):*
> ```cpp
>       : sandbox(sandbox ? sandbox : (abort(), nullptr)),
>         api(api ? api : (abort(), nullptr)) {}
>   absl::StatusOr<std::string> idn2_register_u8(const char *ulabel,
> ```

Since this is a convenience class, we can also accept `const std::string&` or `absl::string_view` as inputs.

Optional, as the names are similar to the upstream library: Rename these to `Idn2RegisterU8`, etc. 
___
*[contrib/libidn2/simple.cc, line 76 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGZvi5E1VsRuDE5e68:-MuGZvi5E1VsRuDE5e69:b41xecf) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L76)):*
> ```cpp
> absl::StatusOr<std::string> IDN2Lib::process_errors(
>     absl::StatusOr<int> untrusted_res, sapi::v::GenericPtr &pt [...]

2022-01-26 21:27 UTC, DemiMarie commented
All review comments should be addressed; I’m waiting to check if it is okay for me to give Reviewable the permissions it has asked for.

2022-01-26 22:53 UTC, DemiMarie reviewed
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/96)* status: 0 of 6 files reviewed, 22 unresolved discussions (waiting on @cblichmann)

___
*[contrib/libidn2/CMakeLists.txt, line 1 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGUJSF5dftGDvfsGb3:-MuMgGzI66ShXHd2o_DA:b-896fix) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/CMakeLists.txt#L1)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Use 2022 for new files
</blockquote></details>

Done.
___
*[contrib/libidn2/CMakeLists.txt, line 15 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGUNyQC0aRdSLnDBu4:-MuMgIOU0qKNtQ0JU9sn:b-896fix) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/CMakeLists.txt#L15)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Please use 3.13. I have a pending PR (#98) that changes the minimum required version to that. 3.13 is included in Debian Buster.
</blockquote></details>

Done.
___
*[contrib/libidn2/CMakeLists.txt, line 36 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGUZR06Jl7iW5xF7MH:-MuMgVIKEZ6-m-4iIVjm:b-896fix) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/CMakeLists.txt#L36)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Formatting: Convert all tabs to spaces
</blockquote></details>

Done.
___
*[contrib/libidn2/CMakeLists.txt, line 38 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGUjJv4KAzxMyMleZu:-MuHnLqcExeDeeBvTYkZ:b-jzs2it) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/CMakeLists.txt#L38)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Does the `PkgConfig` module give us a more distribution-independent way to obtain the full path to the `idn2.h` header?
</blockquote></details>

Indeed it does, will fix.
___
*[contrib/libidn2/CMakeLists.txt, line 52 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGV82y3ZgzopAZ1qYd:-MuHpReq7-5sf25eIlUL:b-n5d2qg) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/CMakeLists.txt#L52)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

This warrants a comment. I.e. why do we need this?
</blockquote></details>

It isn’t needed.
___
*[contrib/libidn2/CMakeLists.txt, line 58 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGVI215ZCoHHiDdYgc:-MuMgfE0AKaufEq3fVSI:b-896fix) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/CMakeLists.txt#L58)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

See my comment in `simple.cc`
</blockquote></details>

Done.
___
*[contrib/libidn2/simple.cc, line 1 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGVL4o6MedpxcY6V_L:-MuMgizuCDc80JS6Nbsk:b-896fix) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L1)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

2022
</blockquote></details>

Done.
___
*[contrib/libidn2/simple.cc, line 29 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGVQRs73BH0wZA9n1A:-MuMgn42Bniyg1XpSPp-:b-896fix) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L29)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Either remove, or use ` = default;`
</blockquote></details>

Done.
___
*[contrib/libidn2/simple.cc, line 32 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGVXfS6ZfISy-5ozMq:-MuMgpqO5om-A423DRAf:b-896fix) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L32)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

The Google style guide leaves it open whether `*` and `&` should be closer to the type or not. SAPI is a bit more oppinionated: Prefer to keep them close to the type.
See https://github.com/google/sandboxed-api/blob/main/.clang-format#L5
</blockquote></details>

Done.
___
*[contrib/libidn2/simple.cc, line 50 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGWbgj5-r2aPQmmOeN:-MuMjMX05Ms7Ytyxeodl:b-896fix) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L50)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

The declaration order of a class should be `public`, `protected`, `private`. We always spell out `private`, even if that's the only block in a class (https://google.github.io/styleguide/cppguide.html#Declaration_Order).

Additionally, members should be declared below functions and end with an underscore (https://google.github.io/styleguide/cppguide.html#Variable_Names).
</blockquote></details>

Done.
___
*[contrib/libidn2/simple.cc, line 52 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGXZTDE5xnX3nHjeVN:-MuMjNnk0J_r8SVrxw2e:b-896fix) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L52)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Function names should use UpperCamelCase (https://google.github.io/styleguide/cppguide.html#Function_Names).
</blockquote></details>

Done.
___
*[contrib/libidn2/simple.cc, line 56 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGYM6K59s3Ffqg3C5Z:-MuMjPQz9qrt5iu3QkMy:b-896fix) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L56)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Prefer `const absl::StatusOr<int>&` here.  We don't consider`absl::Status` and friends to be small enough to incur the cost of copying. Internally, an `absl::Status`/`absl::StatusOr<T>` may even contain a full stack trace.
</blockquote></details>

Done.
___
*[contrib/libidn2/simple.cc, line 64 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuG_1eO88dJlNdfgYZJ:-MuMjQN4AbVW0T6u1pNb:b-896fix) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L64)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

I think it would be sufficient to accept an `Idn2SapiSandbox` as a mutable reference and create an `IDN2Api` ourselves here.
</blockquote></details>

Done.
___
*[contrib/libidn2/simple.cc, line 67 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuG_Wqr-_kkaIrPu4Li:-MuMfzbZ2NUhmI4z6b_7:b-4y518b) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L67)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Since this is a convenience class, we can also accept `const std::string&` or `absl::string_view` as inputs.

Optional, as the names are similar to the upstream library: Rename these to `Idn2RegisterU8`, etc. 
</blockquote></details>

`ulabel` and `alabel` need to be NUL-terminated.  What is the appropriate C++ type to use?
___
*[contrib/libidn2/simple.cc, line 76 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGZvi5E1VsRuDE5e68:- [...]

2022-01-27 17:05 UTC, cblichmann requested changes
> Reviewed 1 of 6 files at r3, 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/96)* status: 5 of 6 files reviewed, 14 unresolved discussions (waiting on @cblichmann and @DemiMarie)

___
*[contrib/libidn2/CMakeLists.txt, line 60 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRRbw24ij3HZk3hcqv:-MuRRbw24ij3HZk3hcqw:bfla7bb) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/CMakeLists.txt#L60)):*
> ```CMake
> )
> 
> if (SAPI_ENABLE_TESTS)
> ```

Nit: In the CMake language, `if()` is a command, just like e.g.`set()`. That means we don't leave a space between `if` and `()`.
___
*[contrib/libidn2/libidn2_sapi.h, line 14 at r3](https://reviewable.io/reviews/google/sandboxed-api/96#-MuMJQer4ZI_vXP1aSuu:-MuMJQes0Fg07YtB-0qI:b-wdlune) ([raw file](https://github.com/google/sandboxed-api/blob/d30a11d0e52eb249dfe97833e3e62e4e283a6027/contrib/libidn2/libidn2_sapi.h#L14)):*
> ```objc
> // See the License for the specific language governing permissions and
> // limitations under the License.
> ```

This should have an include guard:
`#ifndef CONTRIB_LIBIDN2_LIBIDN2_SAPI_H_ ...`
___
*[contrib/libidn2/libidn2_sapi.cc, line 48 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRRwwEBZnhVjYuc7fn:-MuRRwwEBZnhVjYuc7fo:b3ju722) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/libidn2_sapi.cc#L48)):*
> ```cpp
>     return maybe_untrusted_name.status();
>   }
>   // FIXME: sanitize the result
> ```

Any suggestions on how to sanitize the result?
___
*[contrib/libidn2/tests/CMakeLists.txt, line 15 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRS36gCpHG6JbHg1aH:-MuRS36gCpHG6JbHg1aI:b540pa1) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/tests/CMakeLists.txt#L15)):*
> ```CMake
> # limitations under the License.
> 
> cmake_minimum_required(VERSION 3.13)
> ```

As this is a subdirectory CMakeLists.txt, this isn't needed.



_Code quote:_
```CMake
cmake_minimum_required(VERSION 3.13)

project(test CXX C)

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)
```
___
*[contrib/libidn2/tests/CMakeLists.txt, line 27 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRS91GATi_8jx2MlNo:-MuRS91GATi_8jx2MlNp:bggk8hl) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/tests/CMakeLists.txt#L27)):*
> ```CMake
>   libidn2_sapi_wrapper
>   gtest
>   gtest_main
> ```

Replace these  with `sapi::test_main`



_Code quote:_
```CMake
  gtest
  gtest_main
  gmock
```
___
*[contrib/libidn2/tests/libidn2_sapi_test.cc, line 27 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRSLI47qmnvocJx-sj:-MuRSLI47qmnvocJx-sk:bpqckjq) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/tests/libidn2_sapi_test.cc#L27)):*
> ```cpp
>   static std::optional<IDN2Lib> lib_;
>   static void SetUpTestSuite() {
>     auto& sandbox = sandbox_.emplace();
> ```

It actually makes little sense to put this in an `std::optional<>` here, as `SetUpTestSuite` is basically a constructor. So in tests, it will never be unset.

Similar for `lib_`, as the `ASSERT_TRUE()` will abort the test before we enter a `nullopt` state for `lib_`.



_Code quote:_
```cpp
auto& sandbox = sandbox_.emplace();
```
___
*[contrib/libidn2/tests/libidn2_sapi_test.cc, line 28 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRSm5T--20PjJYLNBJ:-MuRSm5T--20PjJYLNBK:b3tkm5e) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/tests/libidn2_sapi_test.cc#L28)):*
> ```cpp
>   static void SetUpTestSuite() {
>     auto& sandbox = sandbox_.emplace();
>     ASSERT_TRUE(sandbox.Init().ok());
> ```

Suggest `ASSERT_THAT(sandbox.Init(), IsOk());` with a suitable `using sapi::IsOk;` near the top.



_Code quote:_
```cpp
ASSERT_TRUE(sandbox.Init().ok());
```
___
*[contrib/libidn2/tests/libidn2_sapi_test.cc, line 34 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRSu4L8dgwbRJRSzTB:-MuRSu4L8dgwbRJRSzTC:b-qlidaz) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/tests/libidn2_sapi_test.cc#L34)):*
> ```cpp
>   static void TearDownTestSuite() {
>     sandbox_.reset();
> ```

Nit: Remove empty line.
___
*[contrib/libidn2/tests/libidn2_sapi_test.cc, line 54 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRT0soDenX5VoVarTN:-MuRT0soDenX5VoVarTO:b-9bmn3f) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/tests/libidn2_sapi_test.cc#L54)):*
> ```cpp
> 
> TEST_F(Idn2SapiSandboxTest, RegisterConversion) {
>   // I could not get this to succeed except on ASCII-only strings
> ```

We should debug this, as this is the whole point, no?
___
*[contrib/libidn2/simple.cc, line 142 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGbkQLCpNGGoxVNqag:-MuRUiVMD4fL1AX_qUoz:b-au99ux) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L142)):*
<details><summary><i>Previously, DemiMarie (Demi Marie Obenour) wrote…</i></summary><blockquote>

Good idea, but I will use an `std::optional` instead of plain new if that is okay.
</blockquote></details>

See my comment in the newer changes. But ultimately up to you.
___
*[contrib/libidn2/simple.cc, line 151 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGaqO04BF33LqXUvlc:-MuRUMy344rS3LgWvVef:bhd6lc6) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L151)):*
<details><summary><i>Previously, DemiMarie (Demi Marie Obenour) wrote…</i></summary><blockquote>

That didn’t compile for me (`::testing::StrEq` not found).  I used `EXPECT_STREQ` instead.
</blockquote></details>

That's probably because of a missing `gmock` include? I know that we ship `StrEq` in the open-source version. But `EXPECT_STREQ` is also fine.
___
*[contrib/libidn2/simple.cc, line 160 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGbR4E6CGH1Ojsjz9R:-MuRUZ_zBeObQy5TUrmZ:bvj07hs) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L160)):*
<details><summary><i>Previously, DemiMarie (Demi Marie Obenour) wrote…</i></summary><blockquote>

This is expected to fail.
</blockquote></details>

Ah sorry, misread that. `Not(IsOk())` it is, then :-)


<!-- Sent from Reviewable.io -->

2022-01-27 22:19 UTC, DemiMarie reviewed
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/96)* status: 2 of 6 files reviewed, 13 unresolved discussions (waiting on @cblichmann)

___
*[contrib/libidn2/libidn2_sapi.h, line 14 at r3](https://reviewable.io/reviews/google/sandboxed-api/96#-MuMJQer4ZI_vXP1aSuu:-MuSbPAR9kPwYCiteOO4:b-896fix) ([raw file](https://github.com/google/sandboxed-api/blob/d30a11d0e52eb249dfe97833e3e62e4e283a6027/contrib/libidn2/libidn2_sapi.h#L14)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

This should have an include guard:
`#ifndef CONTRIB_LIBIDN2_LIBIDN2_SAPI_H_ ...`
</blockquote></details>

Done.
___
*[contrib/libidn2/libidn2_sapi.cc, line 48 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRRwwEBZnhVjYuc7fn:-MuRuYuqEzVkSfXTKYhK:b-4yokz8) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/libidn2_sapi.cc#L48)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Any suggestions on how to sanitize the result?
</blockquote></details>

Check that the return value is valid ASCII (for a-labels) or UTF-8 (for u-labels) and doesn’t have any forbidden characters (such as whitespace, control characters, or metacharacters).
___
*[contrib/libidn2/tests/CMakeLists.txt, line 15 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRS36gCpHG6JbHg1aH:-MuSbV8e9Oxfka0QPt2n:b-896fix) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/tests/CMakeLists.txt#L15)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

As this is a subdirectory CMakeLists.txt, this isn't needed.
</blockquote></details>

Done.
___
*[contrib/libidn2/tests/CMakeLists.txt, line 27 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRS91GATi_8jx2MlNo:-MuS9fB65HhLBGdtHqvP:b-896fix) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/tests/CMakeLists.txt#L27)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Replace these  with `sapi::test_main`
</blockquote></details>

Done.
___
*[contrib/libidn2/tests/libidn2_sapi_test.cc, line 27 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRSLI47qmnvocJx-sj:-MuRvV537JsInvuXIIAz:bhvctio) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/tests/libidn2_sapi_test.cc#L27)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

It actually makes little sense to put this in an `std::optional<>` here, as `SetUpTestSuite` is basically a constructor. So in tests, it will never be unset.

Similar for `lib_`, as the `ASSERT_TRUE()` will abort the test before we enter a `nullopt` state for `lib_`.
</blockquote></details>

As a Rust developer I have a strong dislike for raw pointers, preferring `Option` just about everywhere.  But this is C++, not Rust.
___
*[contrib/libidn2/tests/libidn2_sapi_test.cc, line 28 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRSm5T--20PjJYLNBJ:-MuS9rpA3v9Gdzp528Rn:b-896fix) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/tests/libidn2_sapi_test.cc#L28)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Suggest `ASSERT_THAT(sandbox.Init(), IsOk());` with a suitable `using sapi::IsOk;` near the top.
</blockquote></details>

Done.
___
*[contrib/libidn2/tests/libidn2_sapi_test.cc, line 34 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRSu4L8dgwbRJRSzTB:-MuS9tTV1j0AjJiEBNsm:b-m9xpwf) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/tests/libidn2_sapi_test.cc#L34)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Nit: Remove empty line.
</blockquote></details>

Which one?
___
*[contrib/libidn2/tests/libidn2_sapi_test.cc, line 54 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRT0soDenX5VoVarTN:-MuRxcjdBPgWFSaLMy8L:b-g8d0v3) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/tests/libidn2_sapi_test.cc#L54)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

We should debug this, as this is the whole point, no?
</blockquote></details>

I was expecting `idn2_register_u8` to take a full domain name, but it just takes a label.  Oops!
___
*[contrib/libidn2/simple.cc, line 142 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGbkQLCpNGGoxVNqag:-MuS9yy35Hp5zwXeRdFJ:b-a2ujgl) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L142)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

See my comment in the newer changes. But ultimately up to you.
</blockquote></details>

Changed
___
*[contrib/libidn2/simple.cc, line 151 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGaqO04BF33LqXUvlc:-MuS-9vO0TL80Mx0qsmX:b-o712qe) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L151)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

That's probably because of a missing `gmock` include? I know that we ship `StrEq` in the open-source version. But `EXPECT_STREQ` is also fine.
</blockquote></details>

I was wondering why my program seemed to rely on a system-wide `gtest` and `gmock`; turned out the problem was that I was using CMake incorrectly.
___
*[contrib/libidn2/simple.cc, line 160 at r1](https://reviewable.io/reviews/google/sandboxed-api/96#-MuGbR4E6CGH1Ojsjz9R:-MuSb9qq5urMyHFEpDUn:b-896fix) ([raw file](https://github.com/google/sandboxed-api/blob/82dbf8de5b240037a0893e20225c1b88ca9ec84c/contrib/libidn2/simple.cc#L160)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Ah sorry, misread that. `Not(IsOk())` it is, then :-)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-01-31 16:16 UTC, cblichmann requested changes
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/96)* status: all files reviewed, 9 unresolved discussions (waiting on @cblichmann and @DemiMarie)

___
*[contrib/libidn2/libidn2_sapi.h, line 48 at r5](https://reviewable.io/reviews/google/sandboxed-api/96#-MukuIqb55hEo7yVaNae:-MukuIqb55hEo7yVaNaf:bnm4n3q) ([raw file](https://github.com/google/sandboxed-api/blob/752cd350ab8a9c6d7887f44d6a57f01ec9479512/contrib/libidn2/libidn2_sapi.h#L48)):*
> ```objc
>  public:
>   explicit IDN2Lib(Idn2SapiSandbox* sandbox)
>       : sandbox_(sandbox ? sandbox : (abort(), nullptr)), api_(sandbox_) {}
> ```

For this we have `CHECK_NOTNULL(sandbox)` from glog. I think just including its header should be enough.
Once Abseil releases its logging implementation, the spelling will change to `ABSL_DIE_IF_NULL`.



_Code quote:_
```objc
sandbox_(sandbox ? sandbox : (abort(), nullptr))
```
___
*[contrib/libidn2/libidn2_sapi.cc, line 48 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRRwwEBZnhVjYuc7fn:-MukqEB30CbQtgU-2yLi:b-yav5dg) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/libidn2_sapi.cc#L48)):*
<details><summary><i>Previously, DemiMarie (Demi Marie Obenour) wrote…</i></summary><blockquote>

Check that the return value is valid ASCII (for a-labels) or UTF-8 (for u-labels) and doesn’t have any forbidden characters (such as whitespace, control characters, or metacharacters).
</blockquote></details>

Please add this as a comment, then. Do you want to address this in a follow-up PR?
___
*[contrib/libidn2/tests/libidn2_sapi_test.cc, line 27 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRSLI47qmnvocJx-sj:-MukqUrLEsptOA62KfDw:bwy7axd) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/tests/libidn2_sapi_test.cc#L27)):*
<details><summary><i>Previously, DemiMarie (Demi Marie Obenour) wrote…</i></summary><blockquote>

As a Rust developer I have a strong dislike for raw pointers, preferring `Option` just about everywhere.  But this is C++, not Rust.
</blockquote></details>

¯\_(ツ)_/¯

I get it, but we don't gain much from using `std::optional<>` in this instance.


<!-- Sent from Reviewable.io -->

2022-02-01 01:34 UTC, DemiMarie reviewed
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/96)* status: all files reviewed, 9 unresolved discussions (waiting on @cblichmann)

___
*[contrib/libidn2/libidn2_sapi.h, line 48 at r5](https://reviewable.io/reviews/google/sandboxed-api/96#-MukuIqb55hEo7yVaNae:-Mumuhv11HTDo4vXSJWm:b-896fix) ([raw file](https://github.com/google/sandboxed-api/blob/752cd350ab8a9c6d7887f44d6a57f01ec9479512/contrib/libidn2/libidn2_sapi.h#L48)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

For this we have `CHECK_NOTNULL(sandbox)` from glog. I think just including its header should be enough.
Once Abseil releases its logging implementation, the spelling will change to `ABSL_DIE_IF_NULL`.
</blockquote></details>

Done.
___
*[contrib/libidn2/libidn2_sapi.cc, line 48 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRRwwEBZnhVjYuc7fn:-MumLUkXBG0JtR_QhNt0:b-jna5tr) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/libidn2_sapi.cc#L48)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

Please add this as a comment, then. Do you want to address this in a follow-up PR?
</blockquote></details>

I can try to do some basic sanitization, but I am no expert on domain names, so I could very well get it wrong.  Therefore, I will likely limit myself to charset and length checks.
___
*[contrib/libidn2/tests/libidn2_sapi_test.cc, line 27 at r4](https://reviewable.io/reviews/google/sandboxed-api/96#-MuRSLI47qmnvocJx-sj:-MumM2YO4u645dDQ254Z:bc3ix4j) ([raw file](https://github.com/google/sandboxed-api/blob/1af8d684cb0f1e73f8ab5d77efbaf2d4071adbb9/contrib/libidn2/tests/libidn2_sapi_test.cc#L27)):*
<details><summary><i>Previously, cblichmann (Christian Blichmann) wrote…</i></summary><blockquote>

¯\_(ツ)_/¯

I get it, but we don't gain much from using `std::optional<>` in this instance.
</blockquote></details>

Indeed, using `std::optional<>` gains very little here.


<!-- Sent from Reviewable.io -->

2022-02-02 09:23 UTC, okunz reviewed
Left a reminder for the https, apart from that I leave it up to Christian to give the final LGTM.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/google/sandboxed-api/96#-:-MutjVXO8PS-Ap3XP85z:b-ncdn94)* status: 4 of 6 files reviewed, 10 unresolved discussions (waiting on @cblichmann and @DemiMarie)

___
*[contrib/libidn2/CMakeLists.txt, line 7 at r6](https://reviewable.io/reviews/google/sandboxed-api/96#-MutjR-kBxED7QjcONyN:-MutjR-kBxED7QjcONyO:b-injbfi) ([raw file](https://github.com/google/sandboxed-api/blob/55de8f7fd70f6e14771f55077ae6385c8c7f8cc5/contrib/libidn2/CMakeLists.txt#L7)):*
> ```CMake
> # You may obtain a copy of the License at
> #
> #     http://www.apache.org/licenses/LICENSE-2.0
> ```

NIT reminder s/http/https


<!-- Sent from Reviewable.io -->

2022-02-03 13:52 UTC, closed without merging